# Generated by Django 4.1.4 on 2023-02-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracciones',
            name='fotoAtr',
            field=models.ImageField(blank=True, null=True, upload_to='atr_images'),
        ),
    ]
